### ISSUE TITLE
`k2cli generate file-to-output` operation fails

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2cli#107]
When running `k2cli generate file-to-output` operation fails with the error output below and no template is generated.

**k2cli version**

```
$ k2cli version
1.0.5-alpha+git.sha.e04ae0d98289565ab71424fd7b83072bfaed8f66
```

**Environment**:
- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
Nothing

- **Configuration files (`~/.kraken/config.yaml` or the file passed to `k2cli --config`) **:
All arguments shown in command line above, no config.yaml file is present.

- **Others**:

**What happened**:

```
$ k2cli generate ras-cts-ops.yaml
Pulling image 'quay.io/samsung_cnct/k2:latest' ███▒▒▒▒▒▒▒ Complete
Error response from daemon: invalid bind mount spec ".:.": invalid volume specification: '.:.': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
panic: Error response from daemon: invalid bind mount spec ".:.": invalid volume specification: '.:.': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute

goroutine 1 [running]:
github.com/samsung-cnct/k2cli/cmd.containerAction(0xc4202bb880, 0x1705fe0, 0xc4202fa5a0, 0xc4202c3a40, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/container_helpers.go:337 +0x3a3
github.com/samsung-cnct/k2cli/cmd.runFunc(0x173c440, 0xc42026d310, 0x1, 0x1)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/generate.go:79 +0x2e1
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0x173c440, 0xc42026d290, 0x1, 0x1, 0x173c440, 0xc42026d290)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x173bde0, 0x100649c, 0xc42001c0b8, 0x0)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x173bde0, 0x0, 0x47)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/root.go:65 +0x31
main.main()
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/main.go:23 +0x22
```

**What you expected to happen**:
I expected the equivalent of config.yaml to be generated as ras-cts-ops.yaml per the help text from the command:

```
$ k2cli generate --help
Generate a K2 configuration file at the specified location

Usage:
  k2cli generate [path to save the K2 config file at] (default ) /Users/sostheim/.kraken/config.yaml [flags]
. . . SNIP . . .
```

**How to reproduce it** (as minimally and precisely as possible):

Any user should be able to repro with the same command, substitute the file name of your choice.

**Anything else we need to know**:

Works just fine if you omit an output filename.

```
$ k2cli generate
Pulling image 'quay.io/samsung_cnct/k2:latest' ███▒▒▒▒▒▒▒ Complete
Generated aws config at /Users/sostheim/.kraken/config.yaml
```

**Comment by coffeepac** [comment]
@sostheim can you try passing in a complete path to the desired config file?

**Comment by davidewatson** [comment]
makeMounts() is not prepared to deal with non-absolute paths. Fixing this case is relatively easy, though, since this is most of the k2cli configuration exists as globals, we need to find the right place to fix it.

**Comment by sostheim** [comment]
Absolute paths appear to work fine, thanks for the tip.
```
$ k2cli generate /Users/sostheim/test_config.yaml
Pulling image 'quay.io/samsung_cnct/k2:latest' ██████████ Complete
Generated aws config at /Users/sostheim/test_config.yaml
```

**Comment by alejandroEsc** [comment]
should be fixed with https://github.com/samsung-cnct/k2cli/pull/140
