### ISSUE TITLE
cannot bring up multiple clusters simultaneously

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#58]
Should probably use temporary or generated container names.

```
$ k2cli -k ${HOME}/.kraken/joej2.yaml cluster up
Using k2 config file: /home/jjulian/.kraken/config.yaml
Pulling image 'quay.io/samsung_cnct/k2:latest' █▒▒▒▒▒▒▒▒▒ Complete
Bringing up cluster 'joej' █▒▒▒▒▒▒▒▒▒ Error response from daemon: Conflict. The container name "/k2joej" is already in use by container ec87b137f53ce21375d98d362cdd9a4a460c089255b42c5279ae80ad55fe9252. You have to remove (or rename) that container to be able to reuse that name.
panic: Error response from daemon: Conflict. The container name "/k2joej" is already in use by container ec87b137f53ce21375d98d362cdd9a4a460c089255b42c5279ae80ad55fe9252. You have to remove (or rename) that container to be able to reuse that name.

goroutine 1 [running]:
panic(0x8223a0, 0xc4203120f0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/samsung-cnct/k2cli/cmd.containerAction(0xc4202bf880, 0xabebc0, 0xc42030b440, 0xc42032a300, 0x8, 0x8, 0xc4202e2c90, 0x21, 0x0, 0x0, ...)
	/home/jjulian/dev/k2cli/Godeps/_workspace/src/github.com/samsung-cnct/k2cli/cmd/container_helpers.go:304 +0xa7a
github.com/samsung-cnct/k2cli/cmd.glob..func21(0xae6a40, 0xc4202e4400, 0x0, 0x2)
	/home/jjulian/dev/k2cli/Godeps/_workspace/src/github.com/samsung-cnct/k2cli/cmd/up.go:82 +0x398
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0xae6a40, 0xc4202e40e0, 0x2, 0x2, 0xae6a40, 0xc4202e40e0)
	/home/jjulian/dev/k2cli/Godeps/_workspace/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xae4ea0, 0xc42016dee8, 0x40508b, 0xc420012178)
	/home/jjulian/dev/k2cli/Godeps/_workspace/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xae4ea0, 0xc4200d2b40, 0x0)
	/home/jjulian/dev/k2cli/Godeps/_workspace/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/home/jjulian/dev/k2cli/Godeps/_workspace/src/github.com/samsung-cnct/k2cli/cmd/root.go:63 +0x31
main.main()
	/home/jjulian/dev/k2cli/main.go:23 +0x22
```

**Comment by davidewatson** [comment]
I think the problem is that you did not give each cluster a different name. Can you confirm?

**Comment by joejulian** [comment]
Oops, looks like the -k option didn't work.
